# Workflow to test automatic uploading to Sciebo

name: Upload Testfile 

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Description to be shown in the UI 
        description: 'Filename'
        # Default value if no value is explicitly provided
        default: 'data-YYYY-MM-DD.txt'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "upload"
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Create and Upload a file containing the current date to SCIEBO
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: "crpropa-data"
        path: ".data/"
    - name: Display structure of downloaded files
      run: ls -R
    - name: Compress into tar ball
      run: tar -czf "${{ github.event.inputs.name }}" "./data"
    - name: Upload to sciebo
      shell: bash
      run: curl -u "$SCIEBO_USR:$SCIEBO_PWD" -T  "${{ github.event.inputs.name }}" "https://ruhr-uni-bochum.sciebo.de/public.php/webdav/${{ github.event.inputs.name }}"
      env:
          # Login credentials are stored as encrypted secrets in the repository settings on github.
          SCIEBO_USR: ${{ secrets.SCIEBO_LOGIN }}
          SCIEBO_PWD: ${{ secrets.SCIEBO_PASSWORD}}
          
