# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Filename'
        # Default value if no value is explicitly provided
        default: 'testfile-YYYY-MM-DD.txt'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Create and Upload a file containing the current date to SCIEBO
    - name: Create test file
      run: | 
        date > "${{ github.event.inputs.name }}"
    - name: Upload to sciebo
      shell: bash
      #run: curl -u "$SCIEBO_LOGIN" -T  "${{ github.event.inputs.name }}" "https://ruhr-uni-bochum.sciebo.de/public.php/webdav/${{ github.event.inputs.name }}"
      run: curl -u "$SCIEBO_USR:$SCIEBO_PWD" -T  "${{ github.event.inputs.name }}" "https://ruhr-uni-bochum.sciebo.de/public.php/webdav/${{ github.event.inputs.name }}"
      env:
          SCIEBO_USR: ${{ secrets.SCIEBO_LOGIN }}
          SCIEBO_PWD: ${{ secrets.SCIEBO_PASSWORD}}
          
